### ISSUE TITLE
Nested array

### ISSUE THREAD

**Issue by vsevolodsky** [rsim/ruby-plsql#184]
Good afternoon, there was a problem after updating to 0.7.1 version the procedure which had a nesting with an array does not work, and from the side it is a function accepting an array T_STRING_LIST. Having looked at the code I found out that the nesting counter is not free. Error undefined method `[]` for nil: NilClass - Ruby line (https://github.com/rsim/ruby-plsql/blob/master/lib/plsql/procedure.rb).
Could you possibly modify it for a fee
used stack
Rails 3.2
Ruby 1.9.3
ruby-plsq 0.7.1
Oracle 19
ruby-oci8 2.2.3
